name: LousyNet-SurvivalUtils
version: '${project.version}'
main: info.charlieward.lousynetsurvivalutils.LousyNetSurvivalUtils
api-version: '1.17'
authors:
  - LousyBoi
commands:
  Home:
    description: TPs you to your set home
    usage: /home
  setHome:
    description: Sets your home to current location
    usage : /setHome
